language: javascript

branches:
  only: 
    - master

install:
  - npm install

before_script:
  - npm run build

script:
  - npm test

after_success:
  - git fetch origin
  - git checkout -b travis origin/travis
  - git merge master
  - git checkout master
  - git merge --no-ff travis
  - git push origin master