language: javascript
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
install:
  - npm install
before_script:
  - npm run build
script:
  - npm test
after_success:
   - git config credential.helper "store --file=.git/credentials"
   - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
   - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run release patch; fi
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: dev@uxland.es
  api_key:
    secure: M4dGHm6u4wVjN2bd7vcD5Q0LFfOid2RSrMy1cM2fZQxtm/31zUjFSZeJsayRebVQtLLlPILbZAEIiZx2CTYY4EOigBIaYGGVdoX0AsZHfAiJJCp1RUp5KVvdImmC6fu3pqWoQ8B3ORIrDOk4yvV67yGvVr5nwLuRAgE4RP8yrDaW6xOnBPZeh/Q/n5HM/94p90xI8IXvw+baadHLBy4c0bctnyeag3AQA47bwpAk2uvPQwvDnS2eSV1TNbyWJLs/YHqfcR3D5fu657zqswV1J3j0jOBYG/CnT4NnWrjbNVlYu7ytPQpES0A5xaO3PWGs72uZ7/LAAzwlT9/39C8tn5pC1gPPhY0UuFwrtPjt6eBLyyCa6SuvaBoOSQuInvoNdj7ehkaEQnpXMUoNr/kM25bpQWfvsIa248Z1XlQGZ4b4oYOEJA6/uLlf7cPnwmobcY4rPgaWXLtgOqXNueYrc8DWz13MRXZsSV8FowaCSPTyEQ+29Jeg9uOgkqvrsDE03jf1S9pfg1nwVZ1jo9Caz4u8zEjCxEdlbOP83L7UJBlYvPU1W0J3AUrvq1xyM7xShB2/etxCWUDPVf2IL9dmPexq6/ksdR9DctMe81GlstpPY1CU/XQJuWFxCgy5yDHb/CF5AT7WNJifwqTd8f5e5FXXgZ7Qu58qfsJxAzQrDus=
  on:
    tags: true
    repo: uxland/uxl-utilities
env:
  global:
    secure: xwoG98uLANKGvE0D/2sRceuYO/lzdcqhq7JRjfDYQm6TDZRRfBVDFTkYWySJOyHz4jb5DaPVMuduzmbWeEXhKHSKbRy7N6epJynXm5KKLdORccrd6FMHqRO5B8FBTdtaGKNz9Q/2ZO4PZjIQfo/Onpu/ohHV0iLb9LGBu7w9yrJCRwhgd7m9yBOAO894Fr9hA5vmF5HPlt0hhr3PXJsaCpnujnU4wg+yVoN6xGahHhqHeyx/ZTlsrTdvvi88kxq8PAf1Z6RPFcAyrjdWvtN6sU0zTLHKv46VVMIgjGTuleSUvIyw5tFI8wW1zJSyUJf3NU7DYNk5vZb/FsQdPA5NwcPuESma7nYMX43O7E5IYQIVlXgO8R/nOBreI2k6+at1rQOU0BZ08QMbkBXnkyupcNnb7SA9oa5D38SFp6dNljtCdvVfTamPuJoWmNbfVp1bQ+KSM66DCy51BCgU5GfwVudwjOETTLySNjPn25WyUMKDao08dH62+CJzvks0KnnVqHMv5qL9oXuy6UbBg92wBgAANtM30RQoxORzLfhcEToJy6d1W770qF21BdJuaLqYBz5WToXDH0ZPQvcg19XIYFyRHwvUzNngoiqbYu+mjpzfFhozJve5ExdlLBPSBM8LUrZNInSvCk9UGGBMuCXkNUwpYyVSlYYVXQOmBMzx0lc=
