language: javascript
branches:
  only:
  - master
install:
- npm install
before_script:
- npm run build
script:
- npm test
after_success:
- npm version minor
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: dev@uxland.es
  api_key:
    secure: M4dGHm6u4wVjN2bd7vcD5Q0LFfOid2RSrMy1cM2fZQxtm/31zUjFSZeJsayRebVQtLLlPILbZAEIiZx2CTYY4EOigBIaYGGVdoX0AsZHfAiJJCp1RUp5KVvdImmC6fu3pqWoQ8B3ORIrDOk4yvV67yGvVr5nwLuRAgE4RP8yrDaW6xOnBPZeh/Q/n5HM/94p90xI8IXvw+baadHLBy4c0bctnyeag3AQA47bwpAk2uvPQwvDnS2eSV1TNbyWJLs/YHqfcR3D5fu657zqswV1J3j0jOBYG/CnT4NnWrjbNVlYu7ytPQpES0A5xaO3PWGs72uZ7/LAAzwlT9/39C8tn5pC1gPPhY0UuFwrtPjt6eBLyyCa6SuvaBoOSQuInvoNdj7ehkaEQnpXMUoNr/kM25bpQWfvsIa248Z1XlQGZ4b4oYOEJA6/uLlf7cPnwmobcY4rPgaWXLtgOqXNueYrc8DWz13MRXZsSV8FowaCSPTyEQ+29Jeg9uOgkqvrsDE03jf1S9pfg1nwVZ1jo9Caz4u8zEjCxEdlbOP83L7UJBlYvPU1W0J3AUrvq1xyM7xShB2/etxCWUDPVf2IL9dmPexq6/ksdR9DctMe81GlstpPY1CU/XQJuWFxCgy5yDHb/CF5AT7WNJifwqTd8f5e5FXXgZ7Qu58qfsJxAzQrDus=
  on:
    tags: true
    repo: uxland/uxl-utilities
