language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: 10
before_install:
  - ls -l test/unit
after_success:
  - gulp dist
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
