# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  branches:
    production:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - npm install
            - npm test
            - git config user.name "Alex Vizcaino"
            - git config user.email "avizcaino@uxland.es"
            - git remote set-url origin https://$BITBUCKET_REPO_OWNER:$API_KEY@bitbucket.org/$BITBUCKET_REPO_OWNER/uxl-utilities.git
            - npm run bump-bower
            - npm run bump-version
            - git push origin production:master && git push origin production:master --tags